run:
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go$"

  modules-download-mode: vendor

  build-tags:

linters:
  enable:
    - gofmt
    - govet
    - depguard
    - goimports
    - ineffassign
    - misspell
    - unused
    - revive
    - staticcheck
    - typecheck
    - nolintlint
    - gosec
    - forbidigo
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          # The io/ioutil package has been deprecated.
          # https://go.dev/doc/go1.16#ioutil
          - pkg: "io/ioutil"
            desc: The io/ioutil package has been deprecated.
  forbidigo:
    forbid:
      - '^fmt\.Errorf(# use errors\.Errorf instead)?$'
  gosec:
    excludes:
      - G204  # Audit use of command execution
      - G402  # TLS MinVersion too low
    config:
      G306: "0644"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
    - linters:
        - revive
      text: "empty-block"
    - linters:
        - revive
      text: "superfluous-else"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "redefines-builtin-id"
    - linters:
        - revive
      text: "if-return"

# show all
max-issues-per-linter: 0
max-same-issues: 0
