version: "3"

services:
  db:
    build: .
    command: ./entrypoint.sh
    image: docker.io/tonistiigi/db
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
      args:
        buildno: 1
